version: "2"
services:
  webapp:
    build: .
    working_dir: /1x2network
    image: gradle:7.6-jdk17
    ports:
      - "8080:8080"
    command: gradle bootRun
    volumes:
      - ./:/1x2network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bet_db?createDatabaseIfNotExist=true
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: bet_db
      MYSQL_DB: bet_db

  mysql:
    image: mysql:8.0
    volumes:
      - bet-service-app:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: bet_db
      MYSQL_DATABASE: bet_db

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
volumes:
  bet-service-app: